export const AppImages = {
  LOGO: require('../assets/images/flipkart_logo.png'),
  YELLOW_LOGO: require('../assets/images/f_logo.png'),
  CLOSE_ICON: require('../assets/images/close.png'),
  GROCERY: require('../assets/images/grocery.png'),
  TRAVEL: require('../assets/images/travel.png'),
  PAY: require('../assets/images/pay.png'),
  BANNER_1: require('../assets/images/banner1.jpg'),
  BANNER_2: require('../assets/images/banner2.png'),
  BANNER_3: require('../assets/images/banner3.png'),
  BANNER_4: require('../assets/images/banner4.jpg'),
  BANNER_5: require('../assets/images/banner5.webp'),
  BEAUTY: require('../assets/images/beauty.png'),
  FASHION: require('../assets/images/fashion.jpg'),
  GADGETS: require('../assets/images/gadgets.jpg'),
  HOME: require('../assets/images/home.jpg'),
  APPLIENCE: require('../assets/images/appliences.jpg'),
  FOOD: require('../assets/images/food.jpg'),
  ELECTRONICS: require('../assets/images/electronics.jpg'),
  TOYS: require('../assets/images/toys.jpg'),
  SPORTS: require('../assets/images/sports.jpg'),
  MOBILE: require('../assets/images/mobiles.jpg'),
  SPOYL: require('../assets/images/spoyl.jpg'),
  FURNITURE: require('../assets/images/furniture.jpg'),
  MORE: require('../assets/images/more.jpg'),
};
